version: "3.8"

services:
  db:
    container_name: preifma_db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=preifma_db
      - POSTGRES_USER=preifma_user
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
  # web:
  #   container_name: preifma_api
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DB_NAME=preifma_api
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
  #     - OPENROUTER_PARSER_MODEL=${OPENROUTER_PARSER_MODEL}
  #     - OPENROUTER_EXPLAINER_MODEL=${OPENROUTER_EXPLAINER_MODEL}
  #     - OPENROUTER_SITE_URL=${OPENROUTER_SITE_URL}
  #   depends_on:
  #     - db

volumes:
  postgres_data:
