# Generated by Django 4.2.30 on 2026-05-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_daily_limit',
            field=models.PositiveIntegerField(default=3, help_text='Limite de explicações por IA por dia'),
        ),
    ]
