# Generated by Django 6.0.5 on 2026-05-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ai_daily_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_study_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak',
        ),
    ]
