# Generated by Django 4.2.30 on 2026-05-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Texto de Apoio'), ('image', 'Imagem')], max_length=10)),
                ('content', models.TextField(blank=True, help_text="Usado se for tipo 'text'", null=True)),
                ('file', models.ImageField(blank=True, help_text="Usado se for tipo 'image'", null=True, upload_to='questions/')),
                ('hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Anexo (Biblioteca)',
                'verbose_name_plural': 'Anexos (Biblioteca)',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('integrado', 'Técnico Integrado'), ('subsequente', 'Técnico Subsequente'), ('concomitante', 'Técnico Concomitante')], max_length=20)),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('subject', models.CharField(choices=[('portugues', 'Português'), ('matematica', 'Matemática')], max_length=20)),
                ('statement', models.TextField()),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.attachment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
            options={
                'verbose_name': 'Vínculo de Anexo',
                'verbose_name_plural': 'Vínculos de Anexo',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='attachments',
            field=models.ManyToManyField(related_name='questions', through='exams.QuestionAttachment', to='exams.attachment'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='exams.question')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
        migrations.AddConstraint(
            model_name='alternative',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='exams_unique_correct_alt_per_question'),
        ),
    ]
