# Generated by Django 4.2.30 on 2026-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='label',
            field=models.CharField(blank=True, help_text='Ex: Texto 1, Trecho 2...', max_length=100, null=True),
        ),
    ]
