# Generated by Django 4.2.30 on 2026-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_attachment_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='label',
            field=models.TextField(blank=True, help_text='Ex: Texto 1, Trecho 2...', null=True),
        ),
    ]
