# Generated by Django 4.2.30 on 2026-05-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_attachment_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='label',
            field=models.CharField(blank=True, help_text='Ex: Texto 1, Trecho 2...', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='QuestionExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Texto da explicação gerado pela IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='exams.question')),
            ],
            options={
                'verbose_name': 'Explicação de Questão',
                'verbose_name_plural': 'Explicações de Questões',
            },
        ),
    ]
