# Generated by Django 4.2.30 on 2026-05-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('game', '0002_remove_question_attachments_remove_question_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_letter',
            field=models.CharField(default='', help_text='Letra correta no momento em que o aluno respondeu', max_length=2),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_alternative',
            field=models.ForeignKey(blank=True, help_text='Referência direta à alternativa escolhida (nullable para segurança histórica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='exams.alternative'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Duração total da sessão em segundos'),
        ),
    ]
