# Generated by Django 4.2.30 on 2026-05-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('game', '0003_answer_correct_letter_answer_selected_alternative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='selected_letter',
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_alternative',
            field=models.ForeignKey(help_text='Alternativa escolhida pelo aluno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='exams.alternative'),
        ),
    ]
