# Generated by Django 4.2.30 on 2026-05-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_answer_selected_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermission',
            name='xp_claimed',
            field=models.BooleanField(default=False, help_text='XP da missão já foi creditado ao usuário'),
        ),
    ]
