# Generated by Django 4.2.30 on 2026-05-09 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_add_xp_claimed_to_usermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='special_reward',
            field=models.CharField(blank=True, help_text="Ex: 'AI_LIMIT' para aumentar limite diário de IA", max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserAIDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso Diário de IA',
                'verbose_name_plural': 'Usos Diários de IA',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
