# Generated by Django 4.2.30 on 2026-05-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_mission_special_reward_useraidailyusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
