# Generated by Django 4.2.30 on 2026-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_userachievement_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraidailyusage',
            name='bonus_limit',
            field=models.PositiveIntegerField(default=0, help_text='Bônus extra de cota ganho em missões hoje'),
        ),
    ]
