# Generated by Django 6.0.5 on 2026-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_useraidailyusage_bonus_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='goal_subject',
            field=models.CharField(blank=True, help_text="Ex: 'portugues' ou 'matematica'. Se vazio, conta todas as matérias.", max_length=20, null=True),
        ),
    ]
