# Generated by Django 6.0.5 on 2026-05-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_mission_goal_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='goal_subject',
            field=models.CharField(blank=True, choices=[('portugues', 'Português'), ('matematica', 'Matemática')], help_text='Se vazio, conta todas as matérias.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='goal_type',
            field=models.CharField(choices=[('answer_questions', 'Responder Questões'), ('correct_answers', 'Acertar Questões')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='special_reward',
            field=models.CharField(blank=True, choices=[('AI_LIMIT', '+2 Explicações com IA')], help_text='Recompensa especial além do XP (opcional).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='xp_reward',
            field=models.PositiveIntegerField(choices=[(50, '50 XP'), (100, '100 XP'), (200, '200 XP'), (500, '500 XP'), (1000, '1000 XP')], default=100),
        ),
    ]
