# Generated by Django 6.0.5 on 2026-05-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_mission_goal_subject_alter_mission_goal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='goal_subject',
            field=models.CharField(blank=True, choices=[(None, 'Todas as Matérias (Geral)'), ('portugues', 'Português'), ('matematica', 'Matemática')], help_text='Se vazio, conta todas as matérias.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='xp_reward',
            field=models.PositiveIntegerField(choices=[(50, '50 XP'), (100, '100 XP'), (150, '150 XP'), (200, '200 XP'), (250, '250 XP'), (300, '300 XP')], default=100),
        ),
    ]
