# Generated by Django 4.2.30 on 2026-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_mission_goal_subject_alter_mission_xp_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='xp_reward',
            field=models.PositiveIntegerField(choices=[(50, '50 XP'), (80, '80 XP'), (100, '100 XP'), (120, '120 XP'), (150, '150 XP'), (200, '200 XP')], default=100),
        ),
    ]
